### PR TITLE
Support CMake compile database

### PR DESCRIPTION
**Pull request by bachp**
By using the CMake generated compile database codechecker can run directly after the configure step.

### CODE REVIEW

**Comment by samdolt** [comment]
Thank's for the merge request.  This can really speed-up the build for all software that use a build system with native `compile_database.json` support.

I reviewed your merge request and have three remarks:

- [ ] This only add support to use a `compile_database.json` generated by cmake, but this file is not cmake specific. For example, Meson also has support for it. Maybe it's better to remove any `cmake` specific part and only provide a `CODECHECKER_USE_COMPILE_DATABASE_JSON` or `CODECHECKER_COMPILE_DATABASE_GENERATED_IN_CONFIGURE` variable. 
- [ ] I think it not necessary to add `after do_codecheckeranalyse` in `addtask codecheckerreport after do_codecheckeranalyse` because we already have `bb.build.addtask("codecheckerreport", "do_build", "do_codecheckeranalyse", d)`
- [ ] The readme should be updated to let user know about this feature

**Comment by bachp** [comment]
@samdolt I remove the flag and the compile_database.json is now automatically used if meson or cmake is inherited.

**Comment by samdolt** [comment]
@bachp Thank's. It's a lot cleaner this ways, as the json is automatically used if supported. And so we don't introduce another global variable and also don't have to update the documentation.

For me, this pull request is ready to merge.

**Review by samdolt — APPROVED** [review]

**Comment by bachp** [comment]
I checked this against a meson and cmake project as well as some other build systems (gnutls, openssl). All working so I'm going to merge this

**Pull request merged**
